---
title: "Materials"
---

# Getting Started

## "Syllabus"

Here is a word doc that has some topics about what can be covered ([link](materials/Dark%20R_Syllabus.docx))

## Installing R & R-Studio

Be sure to have the latest versions of R and R-Studio installed. You can do so by navigating to the [Posit Website](https://posit.co/download/rstudio-desktop/). If you have any trouble, you can take a look at [Hands-On Programming with R](https://rstudio-education.github.io/hopr/starting.html).

# Session Materials

## 1-Introduction: An Unexpected Journey

During the first session, we plan to go over becoming more comfortable with R and making it your own. *Note: When I refer to using R, I am really referring to using R-Studio (the GUI for R).* This includes updating some of the default settings in R that will save your environment and all of your data. Having this enabled makes it difficult to practice reproducible coding. Additional steps will include setting up a project, getting familiar with the usage of `packages` and `libraries`, and loading in some data.

Once Dustin puts together some slides, they will be linked here:

-   [Slides for Session 1](/materials/Session1_RStudio.pptx)
-   [Data for Session 1](data/NM-NY_CAS.csv)

## 2-Data Wrangling: And you have my bow!

Our second session will focus on what we do with the data once we have it in the R environment. We will revisit how to bring data into the environment and then begin to talk about descriptives and cleaning. In addition, we will be working to create subscales since that is most of what our research tends to look at. Hopefully, we will be able to make some nice & pretty tables

Once the slides are done, they will go in these empty bullet points:

-   [Slides for Session 2](/slides/2_DataWrangling-speaker.html)

-   
